project/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class AddRecipeForm(FlaskForm):
    recipe_title=StringField('Recipe Title', validators=[DataRequired()])
    recipe_description=StringField('Recipe Description', validators=[DataRequired()])

project/recipes/views.py
from flask import render_template, Blueprint, request, redirect, url_for, flash
from project.models import Recipe
from .forms import AddRecipeForm
from project import db

#Config
recipes_blueprint = Blueprint('recipes', __name__, template_folder='templates')

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field – %s" % (getattr(form, field).label.text,error), 'info')


#routes
@recipes_blueprint.route('/')
def index():
    all_recipes = Recipe.query.all()
    return render_template('recipes.html', recipes = all_recipes)

@recipes_blueprint.route('/add', methods=['GET', 'POST'])
def add_recipe():
    form = AddRecipeForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_recipe = Recipe(form.recipe_title.data, form.recipe_description.data)
            db.session.add(new_recipe)
            db.session.commit()
            flash(f'New recipe, {new_recipe.recipe_title}, added!', 'success')
            return redirect(url_for('recipes.index'))
        else:
            flash_errors(form)
            flash('ERROR. Recipe is not loaded!!!', 'error')
        
    return render_template('add_recipe.html', form=form)    

project/recipes/templates/add_recipe.html
{% extends "layout.html" %}
{% block content %}
 
<div class="add-recipe">
  <div class="page-header">
    <h2>Add a New Recipe</h2>
  </div>
    <form action="{{ url_for('recipes.add_recipe') }}" method="post">
      {{ form.csrf_token }}
      {{ form.recipe_title(placeholder="Recipe Title") }}</br>
      <span class="errors">
          {% if form.recipe_title.errors %}
            {% for error in form.recipe_title.errors %}
              {{ error }}
            {% endfor %}
          {% endif %}
      </span>
      {{ form.recipe_description(placeholder="Recipe Description") }}</br>
      <span class="errors">
        {% if form.recipe_description.errors %}
          {% for error in form.recipe_description.errors %}
            {{ error }}
          {% endfor %}
        {% endif %}
    </span>
      <button class="btn btn-sm btn-success" type="submit">Add Recipe</button>
    </form>
</div>
 
 
{% endblock %}

project/recipes/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Family Recipe App</title>
    <link rel='stylesheet' href="{{ url_for('static', filename='css/main.css') }}">
</head>
<body>
    <h1>Family Recipes App</h1>

    This site describes our favorite family recipes!

    <h2>Breakfest Recipes</h2>
    <h2>Lunch Recipes</h2>
    <h2>Dinner Recipes</h2>
    <h2>Dessert Recipes</h2>
    
</body>
</html>

project/recipes/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Kennedy Family Recipe App">
    <meta name="author" content="Patrick Kennedy">
    <title>Kennedy Family Recipe App</title>
    <!-- styles -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
 
  <body>
 
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
 
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#recipes-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{{ url_for('recipes.index') }}">Kennedy Family Recipes</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="recipes-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Breakfast Recipes</a></li>
            <li><a href="#">Lunch Recipes</a></li>
            <li><a href="#">Dinner Recipes</a></li>
            <li><a href="#">Dessert Recipes</a></li>
            <li><a href="{{ url_for('recipes.add_recipe') }}">Add Recipe</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Welcome!</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!-- /.container -->
    </nav>
 
    <div class="container">
      <div class="content">
        
        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
          <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}
        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
          <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}
        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
          <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
 
        {% endfor %}
        <!-- child template -->
        {% block content %}
        {% endblock %}
 
      </div>
      <div class="footer">
        <hr>
        <p>Patrick Kennedy - 2016</p>
      </div>
    </div><!-- /.container -->
 
    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </body>
</html>

project/recipes/templates/layout2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Kennedy Family Recipe App">
    <meta name="author" content="Patrick Kennedy">
    <title>Kennedy Family Recipe App</title>
    <!-- styles -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
  </head>
 
  <body>
 
    <!-- Static navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="#">Features</a>
            <a class="nav-item nav-link" href="#">Pricing</a>
            <a class="nav-item nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </div>
        </div>
      </nav>
   
      <div class="container">
        <div class="content">
   
          <!-- child template -->
          {% block content %}
          {% endblock %}
   
        </div>
        <div class="footer">
          <hr>
          <p>Patrick Kennedy - 2016</p>
        </div>
      </div><!-- /.container -->
     
    <!-- scripts -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

project/recipes/templates/recipes.html
{% extends "layout.html" %}
{% block content %}
 
<div class="page-header">
  <h2>Recipes</h2>
</div>
<div class="row">
  <div class="col-md-4">
    <table class="table table-striped" id="owned_stock_table">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {% for recipe in recipes %}
        <tr>
          <td>{{ recipe.recipe_title }}</td>
          <td>{{ recipe.recipe_description }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
 
{% endblock %}